BEGIN
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_WORKFLOWGLOBALPARAMETER_TYPE_NAME_TENANTID ON WORKFLOWGLOBALPARAMETER (TYPE, NAME, CASE WHEN TENANTID IS NULL THEN 0 ELSE 1 END, NVL(TENANTID, N''__NULL__''))';
END;
