BEGIN
MERGE INTO WORKFLOWPROCESSINSTANCES target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.ID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;

MERGE INTO WORKFLOWAPPROVALHISTORY target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.PROCESSID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;

MERGE INTO WORKFLOWINBOX target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.PROCESSID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;

MERGE INTO WORKFLOWPROCESSINSTANCEP target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.PROCESSID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;

MERGE INTO WORKFLOWPROCESSTIMER target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.PROCESSID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;

MERGE INTO WORKFLOWPROCESSTRANSITIONH target
USING (
    SELECT ID, TENANTID
    FROM WORKFLOWPROCESSINSTANCE
    WHERE TENANTID IS NOT NULL
) source
ON (source.ID = target.PROCESSID)
WHEN MATCHED THEN
    UPDATE SET target.TENANTID = source.TENANTID
    WHERE target.TENANTID IS NULL OR target.TENANTID <> source.TENANTID;
END;
